### PR TITLE
fixed unnecessary jquery.find() bottleneck

### PR DESCRIPTION
**Pull request by ghost**
I just had a major page (unusual, but not constructed use case) where that line caused 20 seconds delay.

I assume we only want to check if anything matches there. First collecting all and then filtering is unnecessary overhead; in this case it was massive.

### CODE REVIEW

**Comment by ghost** [comment]
Please note that this still isn't optimal; in my case it puts the load down from 20 000 ms to about 600ms (which is still very much for a look of "is there anything")

**Comment by toirl** [comment]
This look **very** promising! I am not sure if "is" behaves in the same way as "find" does. The purpose of this code was to check if there is any visible form element on the currently displayed page. This requires searching within all subelements of the page. If a visible input is found a button to submit is shown, otherwise the button is hidden.
Reading https://api.jquery.com/is/ doesn't brings enlighment to the question what "set" of elements mean.

What was your testcase to check that the application behaves as before?

**Comment by toirl** [comment]
Did you checked if the intended behaviour of this check is still present?

**Comment by ghost** [comment]
@toirl there is indeed a problem. 

hideSubmitButtonOnInputlessPage is called from two places, and the passed parameter is quite different (difference between `jquery('#id')` and `jquery('selector')`: First one returns exactly one element, second one a collection of elements.) 

The result is that after initial (correct) functioning, I cannot switch to another formbar page without losing the button.

I'll look into what I can do about that.

**Comment by ghost** [comment]
I changed the approach now, and tested successfully¹.

A tiny detail is that we now could change the parameters sent to the function, too : Instead of a jquery object we only really need the selector string, but I left that place in the code and worked with the parameters given to the function.

I also rebased my commits on top of the current master, in hope to avoid confusion.


¹: Code is roughly: 
a) hide button
b) select all elements descendant of (selectionstring) 
c) that are also visible inputs, tetxtareas, ... 
d) If they are not no-dirtyable: show submit button, abort execution.

**Pull request merged**
